# Generated by Django 5.0.2 on 2024-02-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
